FROM node:18

WORKDIR /app

COPY package.json .
COPY package-lock.json .  
RUN npm install --force

COPY . .

RUN npm install -g serve@14.2.1

EXPOSE 3000

CMD ["npx", "serve", "-s", "build", "-l", "3000"]